name: Backend Tests
on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install C++ dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev libasio-dev libboost-all-dev libssl-dev
      - name: Install C++ dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew install sqlite3 asio boost openssl
      - name: Install C++ dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install boost-msvc-14.3 --no-progress
          choco install openssl --no-progress
          
      - name: Build C++ project
        run: make
        working-directory: apps/backend
      - name: Run C++ project tests
        run: make run-test
        working-directory: apps/backend